# Copyright (c) 2016 Daichi Teruya
# Released under the MIT license
# http://opensource.org/licenses/mit-license.php
BUILD_SPACE=build_space_project
WORKSPACE_SDK=$(PROJECT_NAME).sdk

SETTING_FILE=builder/settings.tcl

.PHONY: all
all: $(SETTING_FILE) generate_project synthesis implementation export_hardware generate_fsbl generate_bif generate_bootimage

$(SETTING_FILE):
	@echo "*** Generate settings.tcl ***"
	@echo

.PHONY: generate_project
generate_project:
	@echo "*** Generate Project ***"
	@echo

.PHONY: synthesis
synthesis:
	@echo "*** Synthesis ***"
	@echo

.PHONY: implementation
implementation:
	@echo "*** Implementation ***"
	@echo

.PHONY: export_hardware
export_hardware:
	@echo "*** Export Hardware ***"
	@echo

.PHONY: generate_fsbl
generate_fsbl:
	@echo "*** Genarate FSBL ***"
	@echo

.PHONY: generate_bif
generate_bif:
	@echo "*** Genarate BIF ***"
	@echo

.PHONY: generate_bootimage
generate_bootimage:
	@echo "*** Genarate Bootimage ***"
	@echo

